### ISSUE TITLE
"list index out of range"

### ISSUE THREAD

**Issue by rjp** [kootenpv/access_points#21]
```
list index out of range
Line:
                    CFInternet19                   -91  100     Y  -- WPA2(PSK/AES/AES)
Output:
                            SSID BSSID             RSSI CHANNEL HT CC SECURITY (auth/unicast/group)
                    CFInternet19                   -91  100     Y  -- WPA2(PSK/AES/AES)
                    CFInternet19                   -90  36      Y  -- WPA2(PSK/AES/AES)
                         BTWi-fi                   -87  11      Y  -- NONE
                     BTHub6-C3NH                   -87  11      Y  -- WPA2(PSK/AES/AES)
                        BTWifi-X                   -84  1       Y  -- WPA2(802.1x/AES/AES)
                        SKYDAAPC                   -82  1       Y  -- WPA2(PSK/AES/AES)
                   CFL-6BDJ-2.4G                   -61  5,+1    Y  -- WPA(PSK/AES,TKIP/TKIP) WPA2(PSK/AES,TKIP/TKIP)
                        CFL-6BDJ                   -62  64      Y  -- WPA(PSK/AES,TKIP/TKIP) WPA2(PSK/AES,TKIP/TKIP)
```

On macOS Monterey, `12.0 Beta (21A5522h)`.  `Python 3.6.5 |Anaconda, Inc.| (default, Apr 26 2018, 08:42:37)`

(It output one of those chunks for every SSID in the list but I don't think it's useful to provide all of them?)

**Comment by kootenpv** [comment]
What exactly was the full traceback of the error?

**Comment by rjp** [comment]
```

  0%|          | 0/1 [00:00<?, ?it/s]
100%|██████████| 1/1 [00:02<00:00,  2.55s/it]
100%|██████████| 1/1 [00:02<00:00,  2.55s/it]
Please provide the output of the error below this line at github.com/kootenpv/access_points/issues
list index out of range
Line:
                    CFInternet19                   -91  100     Y  -- WPA2(PSK/AES/AES) 
Output:
                            SSID BSSID             RSSI CHANNEL HT CC SECURITY (auth/unicast/group)
                    CFInternet19                   -91  100     Y  -- WPA2(PSK/AES/AES) 
                  TALKTALK28850F                   -86  48      Y  -- WPA2(PSK/AES/AES) 
                    CFInternet19                   -81  8       Y  -- WPA2(PSK/AES/AES) 
                  TALKTALK28850F                   -76  1       Y  -- WPA2(PSK/AES/AES) 
                        SKY2E1D5                   -70  11      Y  -- WPA2(PSK/AES/AES) 
                   CFL-6BDJ-2.4G                   -53  5       Y  -- WPA(PSK/AES,TKIP/TKIP) WPA2(PSK/AES,TKIP/TKIP) 
                        CFL-6BDJ                   -64  64      Y  -- WPA(PSK/AES,TKIP/TKIP) WPA2(PSK/AES,TKIP/TKIP) 

Please provide the output of the error below this line at github.com/kootenpv/access_points/issues
list index out of range
Line:
                  TALKTALK28850F                   -86  48      Y  -- WPA2(PSK/AES/AES) 
Output:
                            SSID BSSID             RSSI CHANNEL HT CC SECURITY (auth/unicast/group)
                    CFInternet19                   -91  100     Y  -- WPA2(PSK/AES/AES) 
                  TALKTALK28850F                   -86  48      Y  -- WPA2(PSK/AES/AES) 
                    CFInternet19                   -81  8       Y  -- WPA2(PSK/AES/AES) 
                  TALKTALK28850F                   -76  1       Y  -- WPA2(PSK/AES/AES) 
                        SKY2E1D5                   -70  11      Y  -- WPA2(PSK/AES/AES) 
                   CFL-6BDJ-2.4G                   -53  5       Y  -- WPA(PSK/AES,TKIP/TKIP) WPA2(PSK/AES,TKIP/TKIP) 
                        CFL-6BDJ                   -64  64      Y  -- WPA(PSK/AES,TKIP/TKIP) WPA2(PSK/AES,TKIP/TKIP) 

Please provide the output of the error below this line at github.com/kootenpv/access_points/issues
list index out of range
Line:
                    CFInternet19                   -81  8       Y  -- WPA2(PSK/AES/AES) 
Output:
                            SSID BSSID             RSSI CHANNEL HT CC SECURITY (auth/unicast/group)
                    CFInternet19                   -91  100     Y  -- WPA2(PSK/AES/AES) 
                  TALKTALK28850F                   -86  48      Y  -- WPA2(PSK/AES/AES) 
                    CFInternet19                   -81  8       Y  -- WPA2(PSK/AES/AES) 
                  TALKTALK28850F                   -76  1       Y  -- WPA2(PSK/AES/AES) 
                        SKY2E1D5                   -70  11      Y  -- WPA2(PSK/AES/AES) 
                   CFL-6BDJ-2.4G                   -53  5       Y  -- WPA(PSK/AES,TKIP/TKIP) WPA2(PSK/AES,TKIP/TKIP) 
                        CFL-6BDJ                   -64  64      Y  -- WPA(PSK/AES,TKIP/TKIP) WPA2(PSK/AES,TKIP/TKIP) 

Please provide the output of the error below this line at github.com/kootenpv/access_points/issues
list index out of range
Line:
                  TALKTALK28850F                   -76  1       Y  -- WPA2(PSK/AES/AES) 
Output:
                            SSID BSSID             RSSI CHANNEL HT CC SECURITY (auth/unicast/group)
                    CFInternet19                   -91  100     Y  -- WPA2(PSK/AES/AES) 
                  TALKTALK28850F                   -86  48      Y  -- WPA2(PSK/AES/AES) 
                    CFInternet19                   -81  8       Y  -- WPA2(PSK/AES/AES) 
                  TALKTALK28850F                   -76  1       Y  -- WPA2(PSK/AES/AES) 
                        SKY2E1D5                   -70  11      Y  -- WPA2(PSK/AES/AES) 
                   CFL-6BDJ-2.4G                   -53  5       Y  -- WPA(PSK/AES,TKIP/TKIP) WPA2(PSK/AES,TKIP/TKIP) 
                        CFL-6BDJ                   -64  64      Y  -- WPA(PSK/AES,TKIP/TKIP) WPA2(PSK/AES,TKIP/TKIP) 

Please provide the output of the error below this line at github.com/kootenpv/access_points/issues
list index out of range
Line:
                        SKY2E1D5                   -70  11      Y  -- WPA2(PSK/AES/AES) 
Output:
                            SSID BSSID             RSSI CHANNEL HT CC SECURITY (auth/unicast/group)
                    CFInternet19                   -91  100     Y  -- WPA2(PSK/AES/AES) 
                  TALKTALK28850F                   -86  48      Y  -- WPA2(PSK/AES/AES) 
                    CFInternet19                   -81  8       Y  -- WPA2(PSK/AES/AES) 
                  TALKTALK28850F                   -76  1       Y  -- WPA2(PSK/AES/AES) 
                        SKY2E1D5                   -70  11      Y  -- WPA2(PSK/AES/AES) 
                   CFL-6BDJ-2.4G                   -53  5       Y  -- WPA(PSK/AES,TKIP/TKIP) WPA2(PSK/AES,TKIP/TKIP) 
                        CFL-6BDJ                   -64  64      Y  -- WPA(PSK/AES,TKIP/TKIP) WPA2(PSK/AES,TKIP/TKIP) 

Please provide the output of the error below this line at github.com/kootenpv/access_points/issues
list index out of range
Line:
                   CFL-6BDJ-2.4G                   -53  5       Y  -- WPA(PSK/AES,TKIP/TKIP) WPA2(PSK/AES,TKIP/TKIP) 
Output:
                            SSID BSSID             RSSI CHANNEL HT CC SECURITY (auth/unicast/group)
                    CFInternet19                   -91  100     Y  -- WPA2(PSK/AES/AES) 
                  TALKTALK28850F                   -86  48      Y  -- WPA2(PSK/AES/AES) 
                    CFInternet19                   -81  8       Y  -- WPA2(PSK/AES/AES) 
                  TALKTALK28850F                   -76  1       Y  -- WPA2(PSK/AES/AES) 
                        SKY2E1D5                   -70  11      Y  -- WPA2(PSK/AES/AES) 
                   CFL-6BDJ-2.4G                   -53  5       Y  -- WPA(PSK/AES,TKIP/TKIP) WPA2(PSK/AES,TKIP/TKIP) 
                        CFL-6BDJ                   -64  64      Y  -- WPA(PSK/AES,TKIP/TKIP) WPA2(PSK/AES,TKIP/TKIP) 

Please provide the output of the error below this line at github.com/kootenpv/access_points/issues
list index out of range
Line:
                        CFL-6BDJ                   -64  64      Y  -- WPA(PSK/AES,TKIP/TKIP) WPA2(PSK/AES,TKIP/TKIP) 
Output:
                            SSID BSSID             RSSI CHANNEL HT CC SECURITY (auth/unicast/group)
                    CFInternet19                   -91  100     Y  -- WPA2(PSK/AES/AES) 
                  TALKTALK28850F                   -86  48      Y  -- WPA2(PSK/AES/AES) 
                    CFInternet19                   -81  8       Y  -- WPA2(PSK/AES/AES) 
                  TALKTALK28850F                   -76  1       Y  -- WPA2(PSK/AES/AES) 
                        SKY2E1D5                   -70  11      Y  -- WPA2(PSK/AES/AES) 
                   CFL-6BDJ-2.4G                   -53  5       Y  -- WPA(PSK/AES,TKIP/TKIP) WPA2(PSK/AES,TKIP/TKIP) 
                        CFL-6BDJ                   -64  64      Y  -- WPA(PSK/AES,TKIP/TKIP) WPA2(PSK/AES,TKIP/TKIP) 

Traceback (most recent call last):
  File "/usr/local/bin/whereami", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/whereami/__main__.py", line 80, in main
    learn(args.location, args.num_samples, args.device)
  File "/usr/local/lib/python3.9/site-packages/whereami/learn.py", line 31, in learn
    train_model()
  File "/usr/local/lib/python3.9/site-packages/whereami/pipeline.py", line 22, in train_model
    raise ValueError("No wifi access points have been found during training")
ValueError: No wifi access points have been found during training
```

**Comment by kootenpv** [comment]
If it actually doesn't fix, please reopen :)
