### ISSUE TITLE
Crashes if wifi isn't enabled on OS X

### ISSUE THREAD

**Issue by bengtb** [kootenpv/access_points#5]
If wifi isn't enabled then this program crashes with a message from which it is hard to understand the root cause:

Traceback (most recent call last):
  File "/Users/bengtb/.virtualenvs/temp2/bin/access_points", line 11, in <module>
    sys.exit(main())
  File "/Users/bengtb/.virtualenvs/temp2/lib/python3.5/site-packages/access_points/__init__.py", line 161, in main
    access_points = wifi_scanner.get_access_points()
  File "/Users/bengtb/.virtualenvs/temp2/lib/python3.5/site-packages/access_points/__init__.py", line 34, in get_access_points
    results = self.parse_output(out)
  File "/Users/bengtb/.virtualenvs/temp2/lib/python3.5/site-packages/access_points/__init__.py", line 60, in parse_output
    for network in read_plist(output):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/plistlib.py", line 1006, in loads
    fp, fmt=fmt, use_builtin_types=use_builtin_types, dict_type=dict_type)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/plistlib.py", line 991, in load
    raise InvalidFileException()
plistlib.InvalidFileException: Invalid file

OS X 10.11.6 running python 3.5.2.

**Comment by kootenpv** [comment]
Thanks for your report. I rolled back the old mechanism. Perhaps try upgrading and see if it works?
`pip install -U --no-cache access_points`

**Comment by bengtb** [comment]
Works beautifully. Thank you!

/Bengt


2016-10-01 13:43 GMT+02:00 Pascal van Kooten <notifications@github.com>:
